<?php
/**
 * @var \Magento\Framework\View\Element\AbstractBlock $block
 * @var string|null $cardholder
 * @var bool $requireCardholder
 */
?>
<!-- 2017-08-25
I have implemented the loader by analogy with:
https://github.com/magento/magento2/blob/2.2.0-rc2.1/app/code/Magento/Checkout/view/frontend/templates/onepage.phtml#L10-L16
-->
<div
	class='loading-mask'
	data-mage-init='{"checkoutLoader": {}}'
	data-role='checkout-loader'
	id='checkout-loader'
>
	<div class='loader'>
		<img
			alt="<?= __('Loading...') ?>"
			src="<?= $block->getViewFileUrl('images/loader-1.gif') ?>"
			style='position: absolute;'
		/>
	</div>
</div>
<!-- 2017-08-26 This container is visible if the «Another card» option is selected, and hidden otherwise. -->
<div class='df-card-new'>
<!-- 2017-10-18
"The payment form in the frontend multishipping scenario does not ask a customer for the cardholder name
even if the «Require the cardholder's name?» option is enabled":
https://github.com/mage2pro/stripe/issues/14 -->
<?php if ($requireCardholder) { ?>
	<div class='field cardholder required'>
		<div class='control'>
			<input
				autocomplete='off'
				class='input-text'
				id='dfe_stripe_cardholder'
				placeholder="<?= __('Cardholder Name') ?>"
				type='text'
				value='<?= df_e($cardholder) ?>'
				data-validate='{required:true}'
			/>
		</div>
	</div>
<?php } ?>
	<!-- 2017-08-25
	Note 1. «Step 2: Create your payment form»: https://stripe.com/docs/elements#create-form
	Note 2. Without this framing <div> the «Pay» button is hidden,
	and even <div>-framing for the button does not giux the button in this case. -->
	<!-- 2017-08-25
	@used-by Dfe_Stripe/multishipping:
		lCard.mount($('.df-stripe-input', element).get(0));
	-->
	<div class='df-stripe-input' data-type='card'></div>
	<!-- 2017-08-25
	The short tag form <div id='card-errors' role='alert' /> does not work here: the «Pay» button is hidden in this case. -->
	<div class='message' role='alert'></div>
	<button class='action primary checkout'>
		<span><?= __('Pay') ?></span>
	</button>
</div>