<?php /** @var \Magento\Framework\View\Element\AbstractBlock $block */ ?>
<!-- 2017-08-25
I have implemented the loader by analogy with:
https://github.com/magento/magento2/blob/2.2.0-rc2.1/app/code/Magento/Checkout/view/frontend/templates/onepage.phtml#L10-L16
-->
<div
	class='loading-mask'
	data-mage-init='{"checkoutLoader": {}}'
	data-role='checkout-loader'
	id='checkout-loader'
>
	<div class='loader'>
		<img
			alt="<?= __('Loading...') ?>"
			src="<?= $block->getViewFileUrl('images/loader-1.gif') ?>"
			style='position: absolute;'
		/>
	</div>
</div>
<!-- 2017-08-26 This container is visible if the «Another card» option is selected, and hidden otherwise. -->
<div class='new-card'>
	<!-- 2017-08-25
	Note 1. «Step 2: Create your payment form»: https://stripe.com/docs/elements#create-form
	Note 2. Without this framing <div> the «Pay» button is hidden,
	and even <div>-framing for the button does not giux the button in this case. -->
	<div class='inputs-container'>
	<!-- 2017-08-25
	@used-by Dfe_Stripe/multishipping:
		card.mount($('.inputs', element).get(0));
	-->
		<div class='inputs'></div>
	<!-- 2017-08-25
	The short tag form <div id='card-errors' role='alert' /> does not work here:
	the «Pay» button is hidden in this case. -->
		<div class='message' role='alert'></div>
	</div>
	<button class='action primary checkout'>
		<span><?= __('Pay') ?></span>
	</button>
</div>